### ISSUE TITLE
请问我该如何阅读这些代码？

### ISSUE THREAD

**Issue by SunspotsInys** [criyle/go-sandbox#1]
我想学习一下你的沙盒实现方法，但是这么多文件完全不知道该从哪里开始理解学习。你能稍微指点一下，可以吗？拜托了

**Comment by criyle** [comment]
如果只是想使用沙盒的话，推荐使用 [go-judge](https://github.com/criyle/go-judge) 提供的 REST API。

我在[个人博客里面有一个简单的介绍](http://criyle.github.io/2020/04/29/go-judge/)。如果要从源码开始看的话可以先看一下 `pkg/forkexec` 的实现，基本上是 go 标准库 `syscall.ForkExec` 的翻版实现。功能在 `runner_linux.go` 中有文档，具体实现在 `fork_child_linux.go` 。目前最新技术沙箱的实现在 `container` 中，可以查看[文档](https://pkg.go.dev/github.com/criyle/go-sandbox@v0.6.7/container)。
