### ISSUE TITLE
Deadlock with RawSyscall in syncWithChild()

### ISSUE THREAD

**Issue by nename0** [criyle/go-sandbox#2]
I found a deadlock when hammering the forkexec-runner with a bunch of executions.

System: Ubuntu Jammy amd64

Steps to reproduce:
- Compile this source: https://gist.github.com/nename0/1d77883609ea26f4f52b35e848a3665e
- Run it with `GOMAXPROCS=4 ./deadlock` (with permissions to create a cgroup e.g. root)
- If the above exits normally, just try again. It might take ~10 tries.
- If the execution is stuck, use `Ctrl+z` to get the parent pid
- Then use `gdb -p <pid>` to attach
- And run `thread apply all bt` in gdb
You will see that four threads are stuck at `RawSyscall()` called from `syncWithChild()` [in Line 117](https://github.com/criyle/go-sandbox/blob/master/pkg/forkexec/fork_linux.go#L117).
This effectively deadlocks the go scheduler.

If you dig a bit you will also see a few forked child pre-exec (all child after exec should be zombies cause of the rlimit).
If you gdb into them they are stuck at `forkAndExecInChild1()` in [Line 427](https://github.com/criyle/go-sandbox/blob/ca60fcad98a57077bd8f5f4651e6518f9ecf237a/pkg/forkexec/fork_child_linux.go#L427).

I'm not really sure whats causes this, why those reads from the socketpair block.
You can fix the symptoms by replacing the `RawSyscall` with `Syscall` like I did in 73c169bfa404fca5129c9067de844cb0beaa74d6.
However im not sure if this fixes the cause or just the symptoms.
Especially because sometimes you get a `runner unknown: broken pipe` output from the execution, even with the above fix.

**Comment by criyle** [comment]
Thank you very much for pointing out the deadlock under high load. Using strace, looks like the program is stucked in read and `SIGURG` loop. So it looks like go scheduler is trying to do passive preempt by sending `SIGURG` to the goroutine who is trying to read child process response by `RawSyscall`. By switching to `Syscall`, it marked the groutine status to `_Gsyscall` so that makes scheduler happy.

The `runner: unknown: broken pipe` is a separate issue where the executable fd overrides the pipe fd. A check was added to avoid fd rewrite.

```
...
[pid 18295] getpid()                    = 18294
[pid 18295] tgkill(18294, 18294, SIGURG <unfinished ...>
[pid 18294] <... read resumed>0xc000016570, 24) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 18295] <... tgkill resumed>)       = 0
[pid 18294] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=18294, si_uid=1000} ---
[pid 18295] getpid( <unfinished ...>
[pid 18294] rt_sigreturn({mask=[]} <unfinished ...>
[pid 18295] <... getpid resumed>)       = 18294
[pid 18294] <... rt_sigreturn resumed>) = 0
[pid 18295] tgkill(18294, 18302, SIGURG <unfinished ...>
[pid 18294] read(12,  <unfinished ...>
[pid 18302] <... read resumed>0xc0000a0168, 24) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 18295] <... tgkill resumed>)       = 0
[pid 18302] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=18294, si_uid=1000} ---
...
```

**Comment by nename0** [comment]
Nice finds. Thanks
