### ISSUE TITLE
作者您好，请问这个沙盒该如何运行呢

### ISSUE THREAD

**Issue by psychocosine** [criyle/go-sandbox#7]
我尝试直接`go run ./cmd/runprog/ ./cmd/runprog/hello` ，发现似乎没有正常运行起来？

![image](https://github.com/user-attachments/assets/a46ef2e2-0cd4-41a1-97be-0082e429f145)

**Comment by psychocosine** [comment]
将`runner`换成`container`就不能运行了，参数设置改了`show-trace-details` ,`cgroup`, `runner`
![image](https://github.com/user-attachments/assets/6f1c7262-dbcf-4cbc-8fd6-058bc943dc30)
运行结果是这样的：
![image](https://github.com/user-attachments/assets/b8ba0de0-7492-496b-bc9f-df6374344813)

**Comment by criyle** [comment]
并不存在 `./cmd/runprog/hello` 可执行文件

**Comment by psychocosine** [comment]
在工作目录中是存在的，需要进行哪些额外配置吗？
![image](https://github.com/user-attachments/assets/1e4b02a1-8069-4271-bf53-6e6102dfba4b)

**Comment by criyle** [comment]
不要使用 go run 而是使用编译好的二进制文件运行。go run 的工作目录不一定是当前目录

**Comment by psychocosine** [comment]
可是使用ptrace可以正常运行：
`go build ./cmd/runprog && ./runprog -show-trace-details -cgroup -runner ptrace ./cmd/runprog/hello`
![image](https://github.com/user-attachments/assets/e194e980-c5c5-4d49-a0da-a5fa6f031c72)

使用container就找不到可执行文件：
`go build ./cmd/runprog && ./runprog -show-trace-details -cgroup -runner container ./cmd/runprog/hello`
![image](https://github.com/user-attachments/assets/1d45b357-e9c7-44fa-9940-49fab56e6f24)

**Comment by criyle** [comment]
默认并没有 bind mount 当前目录，可以修改 main_linux.go 的 150 行左右的配置

**Comment by psychocosine** [comment]
感谢您的指导，挂载 `WithBind("/root", "root", true).` 后再加上-unsafe参数就能运行了。
`./runprog -show-trace-details -unsafe -cgroup -runner container /root/go-sandbox/cmd/runprog/hello `
